project:
  type: website

website:
  title: "star77sa.github.io"
  site-url: https://star77sa.github.io
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
  sidebar:
    style: "docked"
    search: true
    contents: auto
format:
  html:
    theme: cosmo
    css: styles.css
    code-fold: false
    code-line-numbers: true
    code-copy: true


