project:
  type: website
  output-dir: docs

website:
  title: "Time Series"
  site-url: https://star77sa.github.io
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/star77sa
      - icon: rss
        href: index.xml
  sidebar:
    style: "docked"
    search: true
    contents: auto
format:
  html:
    theme: 
      light: Simplex
    css: styles.css
    code-fold: false
    code-line-numbers: true
    code-copy: true


